const cards = [
  {
    name: 'Writing',
    age: 1,
    color: 'blue',
    dogma_resource: 'lightbulbs',
    num_castles: 0,
    num_crowns: 1,
    num_leaves: 0,
    num_lightbulbs: 2,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Clothing',
    age: 1,
    color: 'green',
    dogma_resource: 'leaves',
    num_castles: 0,
    num_crowns: 1,
    num_leaves: 2,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Masonry',
    age: 1,
    color: 'yellow',
    dogma_resource: 'castles',
    num_castles: 3,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Metalworking',
    age: 1,
    color: 'red',
    dogma_resource: 'castles',
    num_castles: 3,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Code of Laws',
    age: 1,
    color: 'purple',
    dogma_resource: 'crowns',
    num_castles: 0,
    num_crowns: 2,
    num_leaves: 1,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Sailing',
    age: 1,
    color: 'green',
    dogma_resource: 'crowns',
    num_castles: 0,
    num_crowns: 2,
    num_leaves: 1,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Pottery',
    age: 1,
    color: 'blue',
    dogma_resource: 'leaves',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 3,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Oars',
    age: 1,
    color: 'red',
    dogma_resource: 'castles',
    num_castles: 2,
    num_crowns: 1,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Archery',
    age: 1,
    color: 'red',
    dogma_resource: 'castles',
    num_castles: 2,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 1,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Agriculture',
    age: 1,
    color: 'yellow',
    dogma_resource: 'leaves',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 3,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Mysticism',
    age: 1,
    color: 'purple',
    dogma_resource: 'castles',
    num_castles: 3,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'City States',
    age: 1,
    color: 'purple',
    dogma_resource: 'crowns',
    num_castles: 1,
    num_crowns: 2,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Domestication',
    age: 1,
    color: 'yellow',
    dogma_resource: 'castles',
    num_castles: 2,
    num_crowns: 1,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Tools',
    age: 1,
    color: 'blue',
    dogma_resource: 'lightbulbs',
    num_castles: 1,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 2,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'The Wheel',
    age: 1,
    color: 'green',
    dogma_resource: 'castles',
    num_castles: 3,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Currency',
    age: 2,
    color: 'green',
    dogma_resource: 'crowns',
    num_castles: 0,
    num_crowns: 2,
    num_leaves: 1,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Canal Building',
    age: 2,
    color: 'yellow',
    dogma_resource: 'crowns',
    num_castles: 0,
    num_crowns: 2,
    num_leaves: 1,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Monotheism',
    age: 2,
    color: 'purple',
    dogma_resource: 'castles',
    num_castles: 3,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Road Building',
    age: 2,
    color: 'red',
    dogma_resource: 'castles',
    num_castles: 3,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Construction',
    age: 2,
    color: 'red',
    dogma_resource: 'castles',
    num_castles: 3,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Fermenting',
    age: 2,
    color: 'yellow',
    dogma_resource: 'leaves',
    num_castles: 1,
    num_crowns: 0,
    num_leaves: 2,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Calendar',
    age: 2,
    color: 'blue',
    dogma_resource: 'leaves',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 2,
    num_lightbulbs: 1,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Philosophy',
    age: 2,
    color: 'purple',
    dogma_resource: 'lightbulbs',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 3,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Mathematics',
    age: 2,
    color: 'blue',
    dogma_resource: 'lightbulbs',
    num_castles: 0,
    num_crowns: 1,
    num_leaves: 0,
    num_lightbulbs: 2,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Mapmaking',
    age: 2,
    color: 'green',
    dogma_resource: 'crowns',
    num_castles: 1,
    num_crowns: 2,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Paper',
    age: 3,
    color: 'green',
    dogma_resource: 'lightbulbs',
    num_castles: 0,
    num_crowns: 1,
    num_leaves: 0,
    num_lightbulbs: 2,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Engineering',
    age: 3,
    color: 'red',
    dogma_resource: 'castles',
    num_castles: 2,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 1,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Translation',
    age: 3,
    color: 'blue',
    dogma_resource: 'crowns',
    num_castles: 0,
    num_crowns: 3,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Feudalism',
    age: 3,
    color: 'purple',
    dogma_resource: 'castles',
    num_castles: 2,
    num_crowns: 0,
    num_leaves: 1,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Machinery',
    age: 3,
    color: 'yellow',
    dogma_resource: 'leaves',
    num_castles: 1,
    num_crowns: 0,
    num_leaves: 2,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Medicine',
    age: 3,
    color: 'yellow',
    dogma_resource: 'leaves',
    num_castles: 0,
    num_crowns: 1,
    num_leaves: 2,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Optics',
    age: 3,
    color: 'red',
    dogma_resource: 'crowns',
    num_castles: 0,
    num_crowns: 3,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Compass',
    age: 3,
    color: 'green',
    dogma_resource: 'crowns',
    num_castles: 0,
    num_crowns: 2,
    num_leaves: 1,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Education',
    age: 3,
    color: 'purple',
    dogma_resource: 'lightbulbs',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 3,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Alchemy',
    age: 3,
    color: 'blue',
    dogma_resource: 'castles',
    num_castles: 2,
    num_crowns: 0,
    num_leaves: 1,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Gunpowder',
    age: 4,
    color: 'red',
    dogma_resource: 'factories',
    num_castles: 0,
    num_crowns: 1,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 2,
    num_timepieces: 0,
  },
  {
    name: 'Invention',
    age: 4,
    color: 'green',
    dogma_resource: 'lightbulbs',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 2,
    num_factories: 1,
    num_timepieces: 0,
  },
  {
    name: 'Colonialism',
    age: 4,
    color: 'red',
    dogma_resource: 'factories',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 1,
    num_factories: 2,
    num_timepieces: 0,
  },
  {
    name: 'Reformation',
    age: 4,
    color: 'purple',
    dogma_resource: 'leaves',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 3,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Anatomy',
    age: 4,
    color: 'yellow',
    dogma_resource: 'leaves',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 3,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Enterprise',
    age: 4,
    color: 'purple',
    dogma_resource: 'crowns',
    num_castles: 0,
    num_crowns: 3,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Perspective',
    age: 4,
    color: 'yellow',
    dogma_resource: 'lightbulbs',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 1,
    num_lightbulbs: 2,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Navigation',
    age: 4,
    color: 'green',
    dogma_resource: 'crowns',
    num_castles: 0,
    num_crowns: 3,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Printing Press',
    age: 4,
    color: 'blue',
    dogma_resource: 'lightbulbs',
    num_castles: 0,
    num_crowns: 1,
    num_leaves: 0,
    num_lightbulbs: 2,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Experimentation',
    age: 4,
    color: 'blue',
    dogma_resource: 'lightbulbs',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 3,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Astronomy',
    age: 5,
    color: 'purple',
    dogma_resource: 'lightbulbs',
    num_castles: 0,
    num_crowns: 1,
    num_leaves: 0,
    num_lightbulbs: 2,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Measurement',
    age: 5,
    color: 'green',
    dogma_resource: 'lightbulbs',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 1,
    num_lightbulbs: 2,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Statistics',
    age: 5,
    color: 'yellow',
    dogma_resource: 'leaves',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 2,
    num_lightbulbs: 1,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Chemistry',
    age: 5,
    color: 'blue',
    dogma_resource: 'factories',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 1,
    num_factories: 2,
    num_timepieces: 0,
  },
  {
    name: 'Coal',
    age: 5,
    color: 'red',
    dogma_resource: 'factories',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 3,
    num_timepieces: 0,
  },
  {
    name: 'The Pirate Code',
    age: 5,
    color: 'red',
    dogma_resource: 'crowns',
    num_castles: 0,
    num_crowns: 2,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 1,
    num_timepieces: 0,
  },
  {
    name: 'Steam Engine',
    age: 5,
    color: 'yellow',
    dogma_resource: 'factories',
    num_castles: 0,
    num_crowns: 1,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 2,
    num_timepieces: 0,
  },
  {
    name: 'Banking',
    age: 5,
    color: 'green',
    dogma_resource: 'crowns',
    num_castles: 0,
    num_crowns: 2,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 1,
    num_timepieces: 0,
  },
  {
    name: 'Physics',
    age: 5,
    color: 'blue',
    dogma_resource: 'lightbulbs',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 2,
    num_factories: 1,
    num_timepieces: 0,
  },
  {
    name: 'Societies',
    age: 5,
    color: 'purple',
    dogma_resource: 'crowns',
    num_castles: 0,
    num_crowns: 2,
    num_leaves: 0,
    num_lightbulbs: 1,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Atomic Theory',
    age: 6,
    color: 'blue',
    dogma_resource: 'lightbulbs',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 3,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Emancipation',
    age: 6,
    color: 'purple',
    dogma_resource: 'factories',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 1,
    num_factories: 2,
    num_timepieces: 0,
  },
  {
    name: 'Vaccination',
    age: 6,
    color: 'yellow',
    dogma_resource: 'leaves',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 2,
    num_lightbulbs: 0,
    num_factories: 1,
    num_timepieces: 0,
  },
  {
    name: 'Classification',
    age: 6,
    color: 'green',
    dogma_resource: 'lightbulbs',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 3,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Metric System',
    age: 6,
    color: 'green',
    dogma_resource: 'crowns',
    num_castles: 0,
    num_crowns: 2,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 1,
    num_timepieces: 0,
  },
  {
    name: 'Encyclopedia',
    age: 6,
    color: 'blue',
    dogma_resource: 'crowns',
    num_castles: 0,
    num_crowns: 3,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Machine Tools',
    age: 6,
    color: 'red',
    dogma_resource: 'factories',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 3,
    num_timepieces: 0,
  },
  {
    name: 'Industrialization',
    age: 6,
    color: 'red',
    dogma_resource: 'factories',
    num_castles: 0,
    num_crowns: 1,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 2,
    num_timepieces: 0,
  },
  {
    name: 'Democracy',
    age: 6,
    color: 'purple',
    dogma_resource: 'lightbulbs',
    num_castles: 0,
    num_crowns: 1,
    num_leaves: 0,
    num_lightbulbs: 2,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Canning',
    age: 6,
    color: 'yellow',
    dogma_resource: 'factories',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 1,
    num_lightbulbs: 0,
    num_factories: 2,
    num_timepieces: 0,
  },
  {
    name: 'Combustion',
    age: 7,
    color: 'red',
    dogma_resource: 'crowns',
    num_castles: 0,
    num_crowns: 2,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 1,
    num_timepieces: 0,
  },
  {
    name: 'Bicycle',
    age: 7,
    color: 'green',
    dogma_resource: 'crowns',
    num_castles: 0,
    num_crowns: 2,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 1,
  },
  {
    name: 'Evolution',
    age: 7,
    color: 'blue',
    dogma_resource: 'lightbulbs',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 3,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Sanitation',
    age: 7,
    color: 'yellow',
    dogma_resource: 'leaves',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 3,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Explosives',
    age: 7,
    color: 'red',
    dogma_resource: 'factories',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 3,
    num_timepieces: 0,
  },
  {
    name: 'Electricity',
    age: 7,
    color: 'green',
    dogma_resource: 'factories',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 1,
    num_factories: 2,
    num_timepieces: 0,
  },
  {
    name: 'Publications',
    age: 7,
    color: 'blue',
    dogma_resource: 'lightbulbs',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 2,
    num_factories: 0,
    num_timepieces: 1,
  },
  {
    name: 'Lighting',
    age: 7,
    color: 'purple',
    dogma_resource: 'leaves',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 2,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 1,
  },
  {
    name: 'Railroad',
    age: 7,
    color: 'purple',
    dogma_resource: 'timepieces',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 1,
    num_timepieces: 2,
  },
  {
    name: 'Refrigeration',
    age: 7,
    color: 'yellow',
    dogma_resource: 'leaves',
    num_castles: 0,
    num_crowns: 1,
    num_leaves: 2,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Antibiotics',
    age: 8,
    color: 'yellow',
    dogma_resource: 'leaves',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 3,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Mobility',
    age: 8,
    color: 'red',
    dogma_resource: 'factories',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 2,
    num_timepieces: 1,
  },
  {
    name: 'Flight',
    age: 8,
    color: 'red',
    dogma_resource: 'crowns',
    num_castles: 0,
    num_crowns: 2,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 1,
  },
  {
    name: 'Rocketry',
    age: 8,
    color: 'blue',
    dogma_resource: 'timepieces',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 3,
  },
  {
    name: 'Skyscrapers',
    age: 8,
    color: 'yellow',
    dogma_resource: 'crowns',
    num_castles: 0,
    num_crowns: 2,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 1,
    num_timepieces: 0,
  },
  {
    name: 'Socialism',
    age: 8,
    color: 'purple',
    dogma_resource: 'leaves',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 3,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Corporations',
    age: 8,
    color: 'green',
    dogma_resource: 'factories',
    num_castles: 0,
    num_crowns: 1,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 2,
    num_timepieces: 0,
  },
  {
    name: 'Mass Media',
    age: 8,
    color: 'green',
    dogma_resource: 'lightbulbs',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 2,
    num_factories: 0,
    num_timepieces: 1,
  },
  {
    name: 'Empiricism',
    age: 8,
    color: 'purple',
    dogma_resource: 'lightbulbs',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 3,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Quantum Theory',
    age: 8,
    color: 'blue',
    dogma_resource: 'timepieces',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 3,
  },
  {
    name: 'Computers',
    age: 9,
    color: 'blue',
    dogma_resource: 'timepieces',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 1,
    num_timepieces: 2,
  },
  {
    name: 'Collaboration',
    age: 9,
    color: 'green',
    dogma_resource: 'crowns',
    num_castles: 0,
    num_crowns: 2,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 1,
  },
  {
    name: 'Genetics',
    age: 9,
    color: 'blue',
    dogma_resource: 'lightbulbs',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 3,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Services',
    age: 9,
    color: 'purple',
    dogma_resource: 'leaves',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 3,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Specialization',
    age: 9,
    color: 'purple',
    dogma_resource: 'factories',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 1,
    num_lightbulbs: 0,
    num_factories: 2,
    num_timepieces: 0,
  },
  {
    name: 'Suburbia',
    age: 9,
    color: 'yellow',
    dogma_resource: 'leaves',
    num_castles: 0,
    num_crowns: 1,
    num_leaves: 2,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Ecology',
    age: 9,
    color: 'yellow',
    dogma_resource: 'lightbulbs',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 1,
    num_lightbulbs: 2,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Fission',
    age: 9,
    color: 'red',
    dogma_resource: 'timepieces',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 3,
  },
  {
    name: 'Satellites',
    age: 9,
    color: 'green',
    dogma_resource: 'timepieces',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 3,
  },
  {
    name: 'Composites',
    age: 9,
    color: 'red',
    dogma_resource: 'factories',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 3,
    num_timepieces: 0,
  },
  {
    name: 'Robotics',
    age: 10,
    color: 'red',
    dogma_resource: 'factories',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 2,
    num_timepieces: 1,
  },
  {
    name: 'Bioengineering',
    age: 10,
    color: 'blue',
    dogma_resource: 'timepieces',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 1,
    num_factories: 0,
    num_timepieces: 2,
  },
  {
    name: 'Databases',
    age: 10,
    color: 'green',
    dogma_resource: 'timepieces',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 3,
  },
  {
    name: 'Miniaturization',
    age: 10,
    color: 'red',
    dogma_resource: 'lightbulbs',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 2,
    num_factories: 0,
    num_timepieces: 1,
  },
  {
    name: 'Software',
    age: 10,
    color: 'blue',
    dogma_resource: 'timepieces',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 3,
  },
  {
    name: 'Self Service',
    age: 10,
    color: 'green',
    dogma_resource: 'crowns',
    num_castles: 0,
    num_crowns: 3,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'A.I.',
    age: 10,
    color: 'purple',
    dogma_resource: 'lightbulbs',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 2,
    num_factories: 0,
    num_timepieces: 1,
  },
  {
    name: 'Stem Cells',
    age: 10,
    color: 'yellow',
    dogma_resource: 'leaves',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 3,
    num_lightbulbs: 0,
    num_factories: 0,
    num_timepieces: 0,
  },
  {
    name: 'Globalization',
    age: 10,
    color: 'yellow',
    dogma_resource: 'factories',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 0,
    num_factories: 3,
    num_timepieces: 0,
  },
  {
    name: 'The Internet',
    age: 10,
    color: 'purple',
    dogma_resource: 'timepieces',
    num_castles: 0,
    num_crowns: 0,
    num_leaves: 0,
    num_lightbulbs: 1,
    num_factories: 0,
    num_timepieces: 2,
  },
];

export default cards;