const Cards = [
  {
    name: 'Writing',
    age: 1,
    color: 'blue',
    dogmaResource: 'lightbulbs',
    numCastles: 0,
    numCrowns: 1,
    numLeaves: 0,
    numLightbulbs: 2,
    numFactories: 0,
    numTimepieces: 0,
    dogma: () => {
      /** Draw a 2. */
      // draw(2);
      // add to hand
    },
  },
  {
    name: 'Clothing',
    age: 1,
    color: 'green',
    dogmaResource: 'leaves',
    numCastles: 0,
    numCrowns: 1,
    numLeaves: 2,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
    dogma: () => {
      /** Meld a card from your hand of a different color from any card on your board. */ 
      // check if any cards in hand not on board
      // select card from hand
      // meld card
  
      /** Draw and score a 1 for each color present on your board not present on any opponent's board. */
      // make list of colors on board
      // loop over other players
      // remove colors found on other player's boards
      // if colors still in list
        // draw x 1's where x = length of remaining list
    },
  },
  {
    name: 'Masonry',
    age: 1,
    color: 'yellow',
    dogmaResource: 'castles',
    numCastles: 3,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
    dogma: () => {
      /** You may meld any number of cards from your hand, each with a Castle. If you melded four or more cards in this way, claim the Monument achievement. */
      // filter hand to create list of only cards with castle resources 
      // player selects x cards from filtered cards
      // meld selected cards
      // if num of melded cards >= 4
        // claim Monument achievement
    },
  },
  {
    name: 'Metalworking',
    age: 1,
    color: 'red',
    dogmaResource: 'castles',
    numCastles: 3,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
    dogma: () => {
      /** Draw and reveal a 1. If it has a Castle, score it and repeat this dogma effect. Otherwise, keep it. */
      // draw(1)
      // reveal card to other players
      // if card has castle resource
        // score(drawnCard)
        // Metalworking()
      // else add to hand
    },
  },
  {
    name: 'Code of Laws',
    age: 1,
    color: 'purple',
    dogmaResource: 'crowns',
    numCastles: 0,
    numCrowns: 2,
    numLeaves: 1,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
    dogma: () => {
      /** You may tuck a card from your hand of the same color as any card on your board. If you do, you may splay that color of your cards left. */
      // filter hand to create list of cards only of colors also present on your board
      // select 1 card from filtered list
      // tuck(selectedCard)
      // as if player wants to splay, and if yes
        // splay(colorOfSelectedCard)
    },
  },
  {
    name: 'Sailing',
    age: 1,
    color: 'green',
    dogmaResource: 'crowns',
    numCastles: 0,
    numCrowns: 2,
    numLeaves: 1,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Pottery',
    age: 1,
    color: 'blue',
    dogmaResource: 'leaves',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 3,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Oars',
    age: 1,
    color: 'red',
    dogmaResource: 'castles',
    numCastles: 2,
    numCrowns: 1,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Archery',
    age: 1,
    color: 'red',
    dogmaResource: 'castles',
    numCastles: 2,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 1,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Agriculture',
    age: 1,
    color: 'yellow',
    dogmaResource: 'leaves',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 3,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Mysticism',
    age: 1,
    color: 'purple',
    dogmaResource: 'castles',
    numCastles: 3,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'City States',
    age: 1,
    color: 'purple',
    dogmaResource: 'crowns',
    numCastles: 1,
    numCrowns: 2,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Domestication',
    age: 1,
    color: 'yellow',
    dogmaResource: 'castles',
    numCastles: 2,
    numCrowns: 1,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Tools',
    age: 1,
    color: 'blue',
    dogmaResource: 'lightbulbs',
    numCastles: 1,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 2,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'The Wheel',
    age: 1,
    color: 'green',
    dogmaResource: 'castles',
    numCastles: 3,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Currency',
    age: 2,
    color: 'green',
    dogmaResource: 'crowns',
    numCastles: 0,
    numCrowns: 2,
    numLeaves: 1,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Canal Building',
    age: 2,
    color: 'yellow',
    dogmaResource: 'crowns',
    numCastles: 0,
    numCrowns: 2,
    numLeaves: 1,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Monotheism',
    age: 2,
    color: 'purple',
    dogmaResource: 'castles',
    numCastles: 3,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Road Building',
    age: 2,
    color: 'red',
    dogmaResource: 'castles',
    numCastles: 3,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Construction',
    age: 2,
    color: 'red',
    dogmaResource: 'castles',
    numCastles: 3,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Fermenting',
    age: 2,
    color: 'yellow',
    dogmaResource: 'leaves',
    numCastles: 1,
    numCrowns: 0,
    numLeaves: 2,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Calendar',
    age: 2,
    color: 'blue',
    dogmaResource: 'leaves',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 2,
    numLightbulbs: 1,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Philosophy',
    age: 2,
    color: 'purple',
    dogmaResource: 'lightbulbs',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 3,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Mathematics',
    age: 2,
    color: 'blue',
    dogmaResource: 'lightbulbs',
    numCastles: 0,
    numCrowns: 1,
    numLeaves: 0,
    numLightbulbs: 2,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Mapmaking',
    age: 2,
    color: 'green',
    dogmaResource: 'crowns',
    numCastles: 1,
    numCrowns: 2,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Paper',
    age: 3,
    color: 'green',
    dogmaResource: 'lightbulbs',
    numCastles: 0,
    numCrowns: 1,
    numLeaves: 0,
    numLightbulbs: 2,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Engineering',
    age: 3,
    color: 'red',
    dogmaResource: 'castles',
    numCastles: 2,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 1,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Translation',
    age: 3,
    color: 'blue',
    dogmaResource: 'crowns',
    numCastles: 0,
    numCrowns: 3,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Feudalism',
    age: 3,
    color: 'purple',
    dogmaResource: 'castles',
    numCastles: 2,
    numCrowns: 0,
    numLeaves: 1,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Machinery',
    age: 3,
    color: 'yellow',
    dogmaResource: 'leaves',
    numCastles: 1,
    numCrowns: 0,
    numLeaves: 2,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Medicine',
    age: 3,
    color: 'yellow',
    dogmaResource: 'leaves',
    numCastles: 0,
    numCrowns: 1,
    numLeaves: 2,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Optics',
    age: 3,
    color: 'red',
    dogmaResource: 'crowns',
    numCastles: 0,
    numCrowns: 3,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Compass',
    age: 3,
    color: 'green',
    dogmaResource: 'crowns',
    numCastles: 0,
    numCrowns: 2,
    numLeaves: 1,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Education',
    age: 3,
    color: 'purple',
    dogmaResource: 'lightbulbs',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 3,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Alchemy',
    age: 3,
    color: 'blue',
    dogmaResource: 'castles',
    numCastles: 2,
    numCrowns: 0,
    numLeaves: 1,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Gunpowder',
    age: 4,
    color: 'red',
    dogmaResource: 'factories',
    numCastles: 0,
    numCrowns: 1,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 2,
    numTimepieces: 0,
  },
  {
    name: 'Invention',
    age: 4,
    color: 'green',
    dogmaResource: 'lightbulbs',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 2,
    numFactories: 1,
    numTimepieces: 0,
  },
  {
    name: 'Colonialism',
    age: 4,
    color: 'red',
    dogmaResource: 'factories',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 1,
    numFactories: 2,
    numTimepieces: 0,
  },
  {
    name: 'Reformation',
    age: 4,
    color: 'purple',
    dogmaResource: 'leaves',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 3,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Anatomy',
    age: 4,
    color: 'yellow',
    dogmaResource: 'leaves',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 3,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Enterprise',
    age: 4,
    color: 'purple',
    dogmaResource: 'crowns',
    numCastles: 0,
    numCrowns: 3,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Perspective',
    age: 4,
    color: 'yellow',
    dogmaResource: 'lightbulbs',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 1,
    numLightbulbs: 2,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Navigation',
    age: 4,
    color: 'green',
    dogmaResource: 'crowns',
    numCastles: 0,
    numCrowns: 3,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Printing Press',
    age: 4,
    color: 'blue',
    dogmaResource: 'lightbulbs',
    numCastles: 0,
    numCrowns: 1,
    numLeaves: 0,
    numLightbulbs: 2,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Experimentation',
    age: 4,
    color: 'blue',
    dogmaResource: 'lightbulbs',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 3,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Astronomy',
    age: 5,
    color: 'purple',
    dogmaResource: 'lightbulbs',
    numCastles: 0,
    numCrowns: 1,
    numLeaves: 0,
    numLightbulbs: 2,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Measurement',
    age: 5,
    color: 'green',
    dogmaResource: 'lightbulbs',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 1,
    numLightbulbs: 2,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Statistics',
    age: 5,
    color: 'yellow',
    dogmaResource: 'leaves',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 2,
    numLightbulbs: 1,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Chemistry',
    age: 5,
    color: 'blue',
    dogmaResource: 'factories',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 1,
    numFactories: 2,
    numTimepieces: 0,
  },
  {
    name: 'Coal',
    age: 5,
    color: 'red',
    dogmaResource: 'factories',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 3,
    numTimepieces: 0,
  },
  {
    name: 'The Pirate Code',
    age: 5,
    color: 'red',
    dogmaResource: 'crowns',
    numCastles: 0,
    numCrowns: 2,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 1,
    numTimepieces: 0,
  },
  {
    name: 'Steam Engine',
    age: 5,
    color: 'yellow',
    dogmaResource: 'factories',
    numCastles: 0,
    numCrowns: 1,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 2,
    numTimepieces: 0,
  },
  {
    name: 'Banking',
    age: 5,
    color: 'green',
    dogmaResource: 'crowns',
    numCastles: 0,
    numCrowns: 2,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 1,
    numTimepieces: 0,
  },
  {
    name: 'Physics',
    age: 5,
    color: 'blue',
    dogmaResource: 'lightbulbs',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 2,
    numFactories: 1,
    numTimepieces: 0,
  },
  {
    name: 'Societies',
    age: 5,
    color: 'purple',
    dogmaResource: 'crowns',
    numCastles: 0,
    numCrowns: 2,
    numLeaves: 0,
    numLightbulbs: 1,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Atomic Theory',
    age: 6,
    color: 'blue',
    dogmaResource: 'lightbulbs',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 3,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Emancipation',
    age: 6,
    color: 'purple',
    dogmaResource: 'factories',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 1,
    numFactories: 2,
    numTimepieces: 0,
  },
  {
    name: 'Vaccination',
    age: 6,
    color: 'yellow',
    dogmaResource: 'leaves',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 2,
    numLightbulbs: 0,
    numFactories: 1,
    numTimepieces: 0,
  },
  {
    name: 'Classification',
    age: 6,
    color: 'green',
    dogmaResource: 'lightbulbs',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 3,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Metric System',
    age: 6,
    color: 'green',
    dogmaResource: 'crowns',
    numCastles: 0,
    numCrowns: 2,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 1,
    numTimepieces: 0,
  },
  {
    name: 'Encyclopedia',
    age: 6,
    color: 'blue',
    dogmaResource: 'crowns',
    numCastles: 0,
    numCrowns: 3,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Machine Tools',
    age: 6,
    color: 'red',
    dogmaResource: 'factories',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 3,
    numTimepieces: 0,
  },
  {
    name: 'Industrialization',
    age: 6,
    color: 'red',
    dogmaResource: 'factories',
    numCastles: 0,
    numCrowns: 1,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 2,
    numTimepieces: 0,
  },
  {
    name: 'Democracy',
    age: 6,
    color: 'purple',
    dogmaResource: 'lightbulbs',
    numCastles: 0,
    numCrowns: 1,
    numLeaves: 0,
    numLightbulbs: 2,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Canning',
    age: 6,
    color: 'yellow',
    dogmaResource: 'factories',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 1,
    numLightbulbs: 0,
    numFactories: 2,
    numTimepieces: 0,
  },
  {
    name: 'Combustion',
    age: 7,
    color: 'red',
    dogmaResource: 'crowns',
    numCastles: 0,
    numCrowns: 2,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 1,
    numTimepieces: 0,
  },
  {
    name: 'Bicycle',
    age: 7,
    color: 'green',
    dogmaResource: 'crowns',
    numCastles: 0,
    numCrowns: 2,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 1,
  },
  {
    name: 'Evolution',
    age: 7,
    color: 'blue',
    dogmaResource: 'lightbulbs',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 3,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Sanitation',
    age: 7,
    color: 'yellow',
    dogmaResource: 'leaves',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 3,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Explosives',
    age: 7,
    color: 'red',
    dogmaResource: 'factories',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 3,
    numTimepieces: 0,
  },
  {
    name: 'Electricity',
    age: 7,
    color: 'green',
    dogmaResource: 'factories',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 1,
    numFactories: 2,
    numTimepieces: 0,
  },
  {
    name: 'Publications',
    age: 7,
    color: 'blue',
    dogmaResource: 'lightbulbs',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 2,
    numFactories: 0,
    numTimepieces: 1,
  },
  {
    name: 'Lighting',
    age: 7,
    color: 'purple',
    dogmaResource: 'leaves',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 2,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 1,
  },
  {
    name: 'Railroad',
    age: 7,
    color: 'purple',
    dogmaResource: 'timepieces',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 1,
    numTimepieces: 2,
  },
  {
    name: 'Refrigeration',
    age: 7,
    color: 'yellow',
    dogmaResource: 'leaves',
    numCastles: 0,
    numCrowns: 1,
    numLeaves: 2,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Antibiotics',
    age: 8,
    color: 'yellow',
    dogmaResource: 'leaves',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 3,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Mobility',
    age: 8,
    color: 'red',
    dogmaResource: 'factories',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 2,
    numTimepieces: 1,
  },
  {
    name: 'Flight',
    age: 8,
    color: 'red',
    dogmaResource: 'crowns',
    numCastles: 0,
    numCrowns: 2,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 1,
  },
  {
    name: 'Rocketry',
    age: 8,
    color: 'blue',
    dogmaResource: 'timepieces',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 3,
  },
  {
    name: 'Skyscrapers',
    age: 8,
    color: 'yellow',
    dogmaResource: 'crowns',
    numCastles: 0,
    numCrowns: 2,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 1,
    numTimepieces: 0,
  },
  {
    name: 'Socialism',
    age: 8,
    color: 'purple',
    dogmaResource: 'leaves',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 3,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Corporations',
    age: 8,
    color: 'green',
    dogmaResource: 'factories',
    numCastles: 0,
    numCrowns: 1,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 2,
    numTimepieces: 0,
  },
  {
    name: 'Mass Media',
    age: 8,
    color: 'green',
    dogmaResource: 'lightbulbs',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 2,
    numFactories: 0,
    numTimepieces: 1,
  },
  {
    name: 'Empiricism',
    age: 8,
    color: 'purple',
    dogmaResource: 'lightbulbs',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 3,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Quantum Theory',
    age: 8,
    color: 'blue',
    dogmaResource: 'timepieces',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 3,
  },
  {
    name: 'Computers',
    age: 9,
    color: 'blue',
    dogmaResource: 'timepieces',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 1,
    numTimepieces: 2,
  },
  {
    name: 'Collaboration',
    age: 9,
    color: 'green',
    dogmaResource: 'crowns',
    numCastles: 0,
    numCrowns: 2,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 1,
  },
  {
    name: 'Genetics',
    age: 9,
    color: 'blue',
    dogmaResource: 'lightbulbs',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 3,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Services',
    age: 9,
    color: 'purple',
    dogmaResource: 'leaves',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 3,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Specialization',
    age: 9,
    color: 'purple',
    dogmaResource: 'factories',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 1,
    numLightbulbs: 0,
    numFactories: 2,
    numTimepieces: 0,
  },
  {
    name: 'Suburbia',
    age: 9,
    color: 'yellow',
    dogmaResource: 'leaves',
    numCastles: 0,
    numCrowns: 1,
    numLeaves: 2,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Ecology',
    age: 9,
    color: 'yellow',
    dogmaResource: 'lightbulbs',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 1,
    numLightbulbs: 2,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Fission',
    age: 9,
    color: 'red',
    dogmaResource: 'timepieces',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 3,
  },
  {
    name: 'Satellites',
    age: 9,
    color: 'green',
    dogmaResource: 'timepieces',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 3,
  },
  {
    name: 'Composites',
    age: 9,
    color: 'red',
    dogmaResource: 'factories',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 3,
    numTimepieces: 0,
  },
  {
    name: 'Robotics',
    age: 10,
    color: 'red',
    dogmaResource: 'factories',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 2,
    numTimepieces: 1,
  },
  {
    name: 'Bioengineering',
    age: 10,
    color: 'blue',
    dogmaResource: 'timepieces',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 1,
    numFactories: 0,
    numTimepieces: 2,
  },
  {
    name: 'Databases',
    age: 10,
    color: 'green',
    dogmaResource: 'timepieces',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 3,
  },
  {
    name: 'Miniaturization',
    age: 10,
    color: 'red',
    dogmaResource: 'lightbulbs',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 2,
    numFactories: 0,
    numTimepieces: 1,
  },
  {
    name: 'Software',
    age: 10,
    color: 'blue',
    dogmaResource: 'timepieces',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 3,
  },
  {
    name: 'Self Service',
    age: 10,
    color: 'green',
    dogmaResource: 'crowns',
    numCastles: 0,
    numCrowns: 3,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'A.I.',
    age: 10,
    color: 'purple',
    dogmaResource: 'lightbulbs',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 2,
    numFactories: 0,
    numTimepieces: 1,
  },
  {
    name: 'Stem Cells',
    age: 10,
    color: 'yellow',
    dogmaResource: 'leaves',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 3,
    numLightbulbs: 0,
    numFactories: 0,
    numTimepieces: 0,
  },
  {
    name: 'Globalization',
    age: 10,
    color: 'yellow',
    dogmaResource: 'factories',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 0,
    numFactories: 3,
    numTimepieces: 0,
  },
  {
    name: 'The Internet',
    age: 10,
    color: 'purple',
    dogmaResource: 'timepieces',
    numCastles: 0,
    numCrowns: 0,
    numLeaves: 0,
    numLightbulbs: 1,
    numFactories: 0,
    numTimepieces: 2,
  },
];

module.exports = Cards;