/**
 * @module  src/reducers/cardsReducer
 * @author  samanthasalley
 * @description handle state for cards.
 * @exports cardsReducer
 */

import produce from 'immer';
import actions from '../actions/actionTypes';

const initialState = {
  cardIds: [],
  cardsById: {},
};

/**
 * @function cardsReducer
 * @param {string} type - dictates which elements of state change
 * @param {any} payload - value to apply to change state
 * @returns updated state
 */
// The immer library allows us to mutate a temporary draft version of the state
// Once our mutations are complete, immer will produce the new state based on the changes
// There's no need for a default case, since immer will return the state unchanged if there
// are no mutations
const cardsReducer = produce((draft, { type, payload }) => {
  switch (type) {
    case actions.SET_CARDS:
      draft.cardIds = payload.cardIds;
      draft.cardsById = payload.cardsById;
      break;
    default:
      return draft;
  }
}, initialState); // initialize state

export default cardsReducer;

// const cardReducer = {
//   cardNames: [
//     'Writing',
//     'Clothing',
//     'Masonry',
//     'Metalworking',
//     'Code of Laws',
//     'Sailing',
//     'Pottery',
//     'Oars',
//     'Archery',
//     'Agriculture',
//     'Mysticism',
//     'City States',
//     'Domestication',
//     'Tools',
//     'The Wheel',
//     'Currency',
//     'Canal Building',
//     'Monotheism',
//     'Road Building',
//     'Construction',
//     'Fermenting',
//     'Calendar',
//     'Philosophy',
//     'Mathematics',
//     'Mapmaking',
//     'Paper',
//     'Engineering',
//     'Translation',
//     'Feudalism',
//     'Machinery',
//     'Medicine',
//     'Optics',
//     'Compass',
//     'Education',
//     'Alchemy',
//     'Gunpowder',
//     'Invention',
//     'Colonialism',
//     'Reformation',
//     'Anatomy',
//     'Enterprise',
//     'Perspective',
//     'Navigation',
//     'Printing Press',
//     'Experimentation',
//     'Astronomy',
//     'Measurement',
//     'Statistics',
//     'Chemistry',
//     'Coal',
//     'The Pirate Code',
//     'Steam Engine',
//     'Banking',
//     'Physics',
//     'Societies',
//     'Atomic Theory',
//     'Emancipation',
//     'Vaccination',
//     'Classification',
//     'Metric System',
//     'Encyclopedia',
//     'Machine Tools',
//     'Industrialization',
//     'Democracy',
//     'Canning',
//     'Combustion',
//     'Bicycle',
//     'Evolution',
//     'Sanitation',
//     'Explosives',
//     'Electricity',
//     'Publications',
//     'Lighting',
//     'Railroad',
//     'Refrigeration',
//     'Antibiotics',
//     'Mobility',
//     'Flight',
//     'Rocketry',
//     'Skyscrapers',
//     'Socialism',
//     'Corporations',
//     'Mass Media',
//     'Empiricism',
//     'Quantum Theory',
//     'Computers',
//     'Collaboration',
//     'Genetics',
//     'Services',
//     'Specialization',
//     'Suburbia',
//     'Ecology',
//     'Fission',
//     'Satellites',
//     'Composites',
//     'Robotics',
//     'Bioengineering',
//     'Databases',
//     'Miniaturization',
//     'Software',
//     'Self Service',
//     'A.I.',
//     'Stem Cells',
//     'Globalization',
//     'The Internet',
//   ],
//   cards: [
//     {
//       name: 'Writing',
//       age: 1,
//       color: 'blue',
//       dogma_resource: 'lightbulbs',
//       num_castles: 0,
//       num_crowns: 1,
//       num_leaves: 0,
//       num_lightbulbs: 2,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: 'lightbulbs',
//       resource_space_4: 'crowns',
//     },
//     {
//       name: 'Clothing',
//       age: 1,
//       color: 'green',
//       dogma_resource: 'leaves',
//       num_castles: 0,
//       num_crowns: 1,
//       num_leaves: 2,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'crowns',
//       resource_space_3: 'leaves',
//       resource_space_4: 'leaves',
//     },
//     {
//       name: 'Masonry',
//       age: 1,
//       color: 'yellow',
//       dogma_resource: 'castles',
//       num_castles: 3,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'castles',
//       resource_space_2: '',
//       resource_space_3: 'castles',
//       resource_space_4: 'castles',
//       special_achievement: 'Monument',
//     },
//     {
//       name: 'Metalworking',
//       age: 1,
//       color: 'red',
//       dogma_resource: 'castles',
//       num_castles: 3,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'castles',
//       resource_space_2: 'castles',
//       resource_space_3: '',
//       resource_space_4: 'castles',
//     },
//     {
//       name: 'Code of Laws',
//       age: 1,
//       color: 'purple',
//       dogma_resource: 'crowns',
//       num_castles: 0,
//       num_crowns: 2,
//       num_leaves: 1,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'crowns',
//       resource_space_3: 'crowns',
//       resource_space_4: 'leaves',
//     },
//     {
//       name: 'Sailing',
//       age: 1,
//       color: 'green',
//       dogma_resource: 'crowns',
//       num_castles: 0,
//       num_crowns: 2,
//       num_leaves: 1,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'crowns',
//       resource_space_2: 'crowns',
//       resource_space_3: '',
//       resource_space_4: 'leaves',
//     },
//     {
//       name: 'Pottery',
//       age: 1,
//       color: 'blue',
//       dogma_resource: 'leaves',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 3,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'leaves',
//       resource_space_3: 'leaves',
//       resource_space_4: 'leaves',
//     },
//     {
//       name: 'Oars',
//       age: 1,
//       color: 'red',
//       dogma_resource: 'castles',
//       num_castles: 2,
//       num_crowns: 1,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'castles',
//       resource_space_2: 'crowns',
//       resource_space_3: '',
//       resource_space_4: 'castles',
//     },
//     {
//       name: 'Archery',
//       age: 1,
//       color: 'red',
//       dogma_resource: 'castles',
//       num_castles: 2,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 1,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'castles',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: '',
//       resource_space_4: 'castles',
//     },
//     {
//       name: 'Agriculture',
//       age: 1,
//       color: 'yellow',
//       dogma_resource: 'leaves',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 3,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'leaves',
//       resource_space_3: 'leaves',
//       resource_space_4: 'leaves',
//     },
//     {
//       name: 'Mysticism',
//       age: 1,
//       color: 'purple',
//       dogma_resource: 'castles',
//       num_castles: 3,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'castles',
//       resource_space_3: 'castles',
//       resource_space_4: 'castles',
//     },
//     {
//       name: 'City States',
//       age: 1,
//       color: 'purple',
//       dogma_resource: 'crowns',
//       num_castles: 1,
//       num_crowns: 2,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'crowns',
//       resource_space_3: 'crowns',
//       resource_space_4: 'castles',
//     },
//     {
//       name: 'Domestication',
//       age: 1,
//       color: 'yellow',
//       dogma_resource: 'castles',
//       num_castles: 2,
//       num_crowns: 1,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'castles',
//       resource_space_2: 'crowns',
//       resource_space_3: '',
//       resource_space_4: 'castles',
//     },
//     {
//       name: 'Tools',
//       age: 1,
//       color: 'blue',
//       dogma_resource: 'lightbulbs',
//       num_castles: 1,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 2,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: 'lightbulbs',
//       resource_space_4: 'castles',
//     },
//     {
//       name: 'The Wheel',
//       age: 1,
//       color: 'green',
//       dogma_resource: 'castles',
//       num_castles: 3,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'castles',
//       resource_space_3: 'castles',
//       resource_space_4: 'castles',
//     },
//     {
//       name: 'Currency',
//       age: 2,
//       color: 'green',
//       dogma_resource: 'crowns',
//       num_castles: 0,
//       num_crowns: 2,
//       num_leaves: 1,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'leaves',
//       resource_space_2: 'crowns',
//       resource_space_3: '',
//       resource_space_4: 'crowns',
//     },
//     {
//       name: 'Canal Building',
//       age: 2,
//       color: 'yellow',
//       dogma_resource: 'crowns',
//       num_castles: 0,
//       num_crowns: 2,
//       num_leaves: 1,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'crowns',
//       resource_space_3: 'leaves',
//       resource_space_4: 'crowns',
//     },
//     {
//       name: 'Monotheism',
//       age: 2,
//       color: 'purple',
//       dogma_resource: 'castles',
//       num_castles: 3,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'castles',
//       resource_space_3: 'castles',
//       resource_space_4: 'castles',
//     },
//     {
//       name: 'Road Building',
//       age: 2,
//       color: 'red',
//       dogma_resource: 'castles',
//       num_castles: 3,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'castles',
//       resource_space_2: 'castles',
//       resource_space_3: '',
//       resource_space_4: 'castles',
//     },
//     {
//       name: 'Construction',
//       age: 2,
//       color: 'red',
//       dogma_resource: 'castles',
//       num_castles: 3,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'castles',
//       resource_space_2: '',
//       resource_space_3: 'castles',
//       resource_space_4: 'castles',
//       special_achievement: 'Empire',
//     },
//     {
//       name: 'Fermenting',
//       age: 2,
//       color: 'yellow',
//       dogma_resource: 'leaves',
//       num_castles: 1,
//       num_crowns: 0,
//       num_leaves: 2,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'leaves',
//       resource_space_2: 'leaves',
//       resource_space_3: '',
//       resource_space_4: 'castles',
//     },
//     {
//       name: 'Calendar',
//       age: 2,
//       color: 'blue',
//       dogma_resource: 'leaves',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 2,
//       num_lightbulbs: 1,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'leaves',
//       resource_space_3: 'leaves',
//       resource_space_4: 'lightbulbs',
//     },
//     {
//       name: 'Philosophy',
//       age: 2,
//       color: 'purple',
//       dogma_resource: 'lightbulbs',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 3,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: 'lightbulbs',
//       resource_space_4: 'lightbulbs',
//     },
//     {
//       name: 'Mathematics',
//       age: 2,
//       color: 'blue',
//       dogma_resource: 'lightbulbs',
//       num_castles: 0,
//       num_crowns: 1,
//       num_leaves: 0,
//       num_lightbulbs: 2,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: 'crowns',
//       resource_space_4: 'lightbulbs',
//     },
//     {
//       name: 'Mapmaking',
//       age: 2,
//       color: 'green',
//       dogma_resource: 'crowns',
//       num_castles: 1,
//       num_crowns: 2,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'crowns',
//       resource_space_3: 'crowns',
//       resource_space_4: 'castles',
//     },
//     {
//       name: 'Paper',
//       age: 3,
//       color: 'green',
//       dogma_resource: 'lightbulbs',
//       num_castles: 0,
//       num_crowns: 1,
//       num_leaves: 0,
//       num_lightbulbs: 2,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: 'lightbulbs',
//       resource_space_4: 'crowns',
//     },
//     {
//       name: 'Engineering',
//       age: 3,
//       color: 'red',
//       dogma_resource: 'castles',
//       num_castles: 2,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 1,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'castles',
//       resource_space_2: '',
//       resource_space_3: 'lightbulbs',
//       resource_space_4: 'castles',
//     },
//     {
//       name: 'Translation',
//       age: 3,
//       color: 'blue',
//       dogma_resource: 'crowns',
//       num_castles: 0,
//       num_crowns: 3,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'crowns',
//       resource_space_3: 'crowns',
//       resource_space_4: 'crowns',
//       special_achievement: 'World',
//     },
//     {
//       name: 'Feudalism',
//       age: 3,
//       color: 'purple',
//       dogma_resource: 'castles',
//       num_castles: 2,
//       num_crowns: 0,
//       num_leaves: 1,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'castles',
//       resource_space_3: 'leaves',
//       resource_space_4: 'castles',
//     },
//     {
//       name: 'Machinery',
//       age: 3,
//       color: 'yellow',
//       dogma_resource: 'leaves',
//       num_castles: 1,
//       num_crowns: 0,
//       num_leaves: 2,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'leaves',
//       resource_space_2: 'leaves',
//       resource_space_3: '',
//       resource_space_4: 'castles',
//     },
//     {
//       name: 'Medicine',
//       age: 3,
//       color: 'yellow',
//       dogma_resource: 'leaves',
//       num_castles: 0,
//       num_crowns: 1,
//       num_leaves: 2,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'crowns',
//       resource_space_2: 'leaves',
//       resource_space_3: 'leaves',
//       resource_space_4: '',
//     },
//     {
//       name: 'Optics',
//       age: 3,
//       color: 'red',
//       dogma_resource: 'crowns',
//       num_castles: 0,
//       num_crowns: 3,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'crowns',
//       resource_space_2: 'crowns',
//       resource_space_3: 'crowns',
//       resource_space_4: '',
//     },
//     {
//       name: 'Compass',
//       age: 3,
//       color: 'green',
//       dogma_resource: 'crowns',
//       num_castles: 0,
//       num_crowns: 2,
//       num_leaves: 1,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'crowns',
//       resource_space_3: 'crowns',
//       resource_space_4: 'leaves',
//     },
//     {
//       name: 'Education',
//       age: 3,
//       color: 'purple',
//       dogma_resource: 'lightbulbs',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 3,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'lightbulbs',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: 'lightbulbs',
//       resource_space_4: '',
//     },
//     {
//       name: 'Alchemy',
//       age: 3,
//       color: 'blue',
//       dogma_resource: 'castles',
//       num_castles: 2,
//       num_crowns: 0,
//       num_leaves: 1,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'leaves',
//       resource_space_3: 'castles',
//       resource_space_4: 'castles',
//     },
//     {
//       name: 'Gunpowder',
//       age: 4,
//       color: 'red',
//       dogma_resource: 'factories',
//       num_castles: 0,
//       num_crowns: 1,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 2,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'factories',
//       resource_space_3: 'crowns',
//       resource_space_4: 'factories',
//     },
//     {
//       name: 'Invention',
//       age: 4,
//       color: 'green',
//       dogma_resource: 'lightbulbs',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 2,
//       num_factories: 1,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: 'lightbulbs',
//       resource_space_4: 'factories',
//       special_achievement: 'Wonder',
//     },
//     {
//       name: 'Colonialism',
//       age: 4,
//       color: 'red',
//       dogma_resource: 'factories',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 1,
//       num_factories: 2,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'factories',
//       resource_space_3: 'lightbulbs',
//       resource_space_4: 'factories',
//     },
//     {
//       name: 'Reformation',
//       age: 4,
//       color: 'purple',
//       dogma_resource: 'leaves',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 3,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'leaves',
//       resource_space_2: 'leaves',
//       resource_space_3: '',
//       resource_space_4: 'leaves',
//     },
//     {
//       name: 'Anatomy',
//       age: 4,
//       color: 'yellow',
//       dogma_resource: 'leaves',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 3,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'leaves',
//       resource_space_2: 'leaves',
//       resource_space_3: 'leaves',
//       resource_space_4: '',
//     },
//     {
//       name: 'Enterprise',
//       age: 4,
//       color: 'purple',
//       dogma_resource: 'crowns',
//       num_castles: 0,
//       num_crowns: 3,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'crowns',
//       resource_space_3: 'crowns',
//       resource_space_4: 'crowns',
//     },
//     {
//       name: 'Perspective',
//       age: 4,
//       color: 'yellow',
//       dogma_resource: 'lightbulbs',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 1,
//       num_lightbulbs: 2,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: 'lightbulbs',
//       resource_space_4: 'leaves',
//     },
//     {
//       name: 'Navigation',
//       age: 4,
//       color: 'green',
//       dogma_resource: 'crowns',
//       num_castles: 0,
//       num_crowns: 3,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'crowns',
//       resource_space_3: 'crowns',
//       resource_space_4: 'crowns',
//     },
//     {
//       name: 'Printing Press',
//       age: 4,
//       color: 'blue',
//       dogma_resource: 'lightbulbs',
//       num_castles: 0,
//       num_crowns: 1,
//       num_leaves: 0,
//       num_lightbulbs: 2,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: 'lightbulbs',
//       resource_space_4: 'crowns',
//     },
//     {
//       name: 'Experimentation',
//       age: 4,
//       color: 'blue',
//       dogma_resource: 'lightbulbs',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 3,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: 'lightbulbs',
//       resource_space_4: 'lightbulbs',
//     },
//     {
//       name: 'Astronomy',
//       age: 5,
//       color: 'purple',
//       dogma_resource: 'lightbulbs',
//       num_castles: 0,
//       num_crowns: 1,
//       num_leaves: 0,
//       num_lightbulbs: 2,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'crowns',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: 'lightbulbs',
//       resource_space_4: '',
//       special_achievement: 'Universe',
//     },
//     {
//       name: 'Measurement',
//       age: 5,
//       color: 'green',
//       dogma_resource: 'lightbulbs',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 1,
//       num_lightbulbs: 2,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'lightbulbs',
//       resource_space_2: 'leaves',
//       resource_space_3: 'lightbulbs',
//       resource_space_4: '',
//     },
//     {
//       name: 'Statistics',
//       age: 5,
//       color: 'yellow',
//       dogma_resource: 'leaves',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 2,
//       num_lightbulbs: 1,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'leaves',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: 'leaves',
//       resource_space_4: '',
//     },
//     {
//       name: 'Chemistry',
//       age: 5,
//       color: 'blue',
//       dogma_resource: 'factories',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 1,
//       num_factories: 2,
//       num_timepieces: 0,
//       resource_space_1: 'factories',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: 'factories',
//       resource_space_4: '',
//     },
//     {
//       name: 'Coal',
//       age: 5,
//       color: 'red',
//       dogma_resource: 'factories',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 3,
//       num_timepieces: 0,
//       resource_space_1: 'factories',
//       resource_space_2: 'factories',
//       resource_space_3: 'factories',
//       resource_space_4: '',
//     },
//     {
//       name: 'The Pirate Code',
//       age: 5,
//       color: 'red',
//       dogma_resource: 'crowns',
//       num_castles: 0,
//       num_crowns: 2,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 1,
//       num_timepieces: 0,
//       resource_space_1: 'crowns',
//       resource_space_2: 'factories',
//       resource_space_3: 'crowns',
//       resource_space_4: '',
//     },
//     {
//       name: 'Steam Engine',
//       age: 5,
//       color: 'yellow',
//       dogma_resource: 'factories',
//       num_castles: 0,
//       num_crowns: 1,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 2,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'factories',
//       resource_space_3: 'crowns',
//       resource_space_4: 'factories',
//     },
//     {
//       name: 'Banking',
//       age: 5,
//       color: 'green',
//       dogma_resource: 'crowns',
//       num_castles: 0,
//       num_crowns: 2,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 1,
//       num_timepieces: 0,
//       resource_space_1: 'factories',
//       resource_space_2: 'crowns',
//       resource_space_3: '',
//       resource_space_4: 'crowns',
//     },
//     {
//       name: 'Physics',
//       age: 5,
//       color: 'blue',
//       dogma_resource: 'lightbulbs',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 2,
//       num_factories: 1,
//       num_timepieces: 0,
//       resource_space_1: 'factories',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: 'lightbulbs',
//       resource_space_4: '',
//     },
//     {
//       name: 'Societies',
//       age: 5,
//       color: 'purple',
//       dogma_resource: 'crowns',
//       num_castles: 0,
//       num_crowns: 2,
//       num_leaves: 0,
//       num_lightbulbs: 1,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'crowns',
//       resource_space_2: '',
//       resource_space_3: 'lightbulbs',
//       resource_space_4: 'crowns',
//     },
//     {
//       name: 'Atomic Theory',
//       age: 6,
//       color: 'blue',
//       dogma_resource: 'lightbulbs',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 3,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'lightbulbs',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: 'lightbulbs',
//       resource_space_4: '',
//     },
//     {
//       name: 'Emancipation',
//       age: 6,
//       color: 'purple',
//       dogma_resource: 'factories',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 1,
//       num_factories: 2,
//       num_timepieces: 0,
//       resource_space_1: 'factories',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: 'factories',
//       resource_space_4: '',
//     },
//     {
//       name: 'Vaccination',
//       age: 6,
//       color: 'yellow',
//       dogma_resource: 'leaves',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 2,
//       num_lightbulbs: 0,
//       num_factories: 1,
//       num_timepieces: 0,
//       resource_space_1: 'leaves',
//       resource_space_2: 'factories',
//       resource_space_3: 'leaves',
//       resource_space_4: '',
//     },
//     {
//       name: 'Classification',
//       age: 6,
//       color: 'green',
//       dogma_resource: 'lightbulbs',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 3,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'lightbulbs',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: 'lightbulbs',
//       resource_space_4: '',
//     },
//     {
//       name: 'Metric System',
//       age: 6,
//       color: 'green',
//       dogma_resource: 'crowns',
//       num_castles: 0,
//       num_crowns: 2,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 1,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'factories',
//       resource_space_3: 'crowns',
//       resource_space_4: 'crowns',
//     },
//     {
//       name: 'Encyclopedia',
//       age: 6,
//       color: 'blue',
//       dogma_resource: 'crowns',
//       num_castles: 0,
//       num_crowns: 3,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'crowns',
//       resource_space_3: 'crowns',
//       resource_space_4: 'crowns',
//     },
//     {
//       name: 'Machine Tools',
//       age: 6,
//       color: 'red',
//       dogma_resource: 'factories',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 3,
//       num_timepieces: 0,
//       resource_space_1: 'factories',
//       resource_space_2: 'factories',
//       resource_space_3: '',
//       resource_space_4: 'factories',
//     },
//     {
//       name: 'Industrialization',
//       age: 6,
//       color: 'red',
//       dogma_resource: 'factories',
//       num_castles: 0,
//       num_crowns: 1,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 2,
//       num_timepieces: 0,
//       resource_space_1: 'crowns',
//       resource_space_2: 'factories',
//       resource_space_3: 'factories',
//       resource_space_4: '',
//     },
//     {
//       name: 'Democracy',
//       age: 6,
//       color: 'purple',
//       dogma_resource: 'lightbulbs',
//       num_castles: 0,
//       num_crowns: 1,
//       num_leaves: 0,
//       num_lightbulbs: 2,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'crowns',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: 'lightbulbs',
//       resource_space_4: '',
//     },
//     {
//       name: 'Canning',
//       age: 6,
//       color: 'yellow',
//       dogma_resource: 'factories',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 1,
//       num_lightbulbs: 0,
//       num_factories: 2,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'factories',
//       resource_space_3: 'leaves',
//       resource_space_4: 'factories',
//     },
//     {
//       name: 'Combustion',
//       age: 7,
//       color: 'red',
//       dogma_resource: 'crowns',
//       num_castles: 0,
//       num_crowns: 2,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 1,
//       num_timepieces: 0,
//       resource_space_1: 'crowns',
//       resource_space_2: 'crowns',
//       resource_space_3: 'factories',
//       resource_space_4: '',
//     },
//     {
//       name: 'Bicycle',
//       age: 7,
//       color: 'green',
//       dogma_resource: 'crowns',
//       num_castles: 0,
//       num_crowns: 2,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 1,
//       resource_space_1: 'crowns',
//       resource_space_2: 'crowns',
//       resource_space_3: 'timepieces',
//       resource_space_4: '',
//     },
//     {
//       name: 'Evolution',
//       age: 7,
//       color: 'blue',
//       dogma_resource: 'lightbulbs',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 3,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'lightbulbs',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: 'lightbulbs',
//       resource_space_4: '',
//     },
//     {
//       name: 'Sanitation',
//       age: 7,
//       color: 'yellow',
//       dogma_resource: 'leaves',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 3,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'leaves',
//       resource_space_2: 'leaves',
//       resource_space_3: '',
//       resource_space_4: 'leaves',
//     },
//     {
//       name: 'Explosives',
//       age: 7,
//       color: 'red',
//       dogma_resource: 'factories',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 3,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'factories',
//       resource_space_3: 'factories',
//       resource_space_4: 'factories',
//     },
//     {
//       name: 'Electricity',
//       age: 7,
//       color: 'green',
//       dogma_resource: 'factories',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 1,
//       num_factories: 2,
//       num_timepieces: 0,
//       resource_space_1: 'lightbulbs',
//       resource_space_2: 'factories',
//       resource_space_3: '',
//       resource_space_4: 'factories',
//     },
//     {
//       name: 'Publications',
//       age: 7,
//       color: 'blue',
//       dogma_resource: 'lightbulbs',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 2,
//       num_factories: 0,
//       num_timepieces: 1,
//       resource_space_1: '',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: 'timepieces',
//       resource_space_4: 'lightbulbs',
//     },
//     {
//       name: 'Lighting',
//       age: 7,
//       color: 'purple',
//       dogma_resource: 'leaves',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 2,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 1,
//       resource_space_1: '',
//       resource_space_2: 'leaves',
//       resource_space_3: 'timepieces',
//       resource_space_4: 'leaves',
//     },
//     {
//       name: 'Railroad',
//       age: 7,
//       color: 'purple',
//       dogma_resource: 'timepieces',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 1,
//       num_timepieces: 2,
//       resource_space_1: 'timepieces',
//       resource_space_2: 'factories',
//       resource_space_3: 'timepieces',
//       resource_space_4: '',
//     },
//     {
//       name: 'Refrigeration',
//       age: 7,
//       color: 'yellow',
//       dogma_resource: 'leaves',
//       num_castles: 0,
//       num_crowns: 1,
//       num_leaves: 2,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'leaves',
//       resource_space_3: 'leaves',
//       resource_space_4: 'crowns',
//     },
//     {
//       name: 'Antibiotics',
//       age: 8,
//       color: 'yellow',
//       dogma_resource: 'leaves',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 3,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'leaves',
//       resource_space_2: 'leaves',
//       resource_space_3: 'leaves',
//       resource_space_4: '',
//     },
//     {
//       name: 'Mobility',
//       age: 8,
//       color: 'red',
//       dogma_resource: 'factories',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 2,
//       num_timepieces: 1,
//       resource_space_1: '',
//       resource_space_2: 'factories',
//       resource_space_3: 'timepieces',
//       resource_space_4: 'factories',
//     },
//     {
//       name: 'Flight',
//       age: 8,
//       color: 'red',
//       dogma_resource: 'crowns',
//       num_castles: 0,
//       num_crowns: 2,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 1,
//       resource_space_1: 'crowns',
//       resource_space_2: '',
//       resource_space_3: 'timepieces',
//       resource_space_4: 'crowns',
//     },
//     {
//       name: 'Rocketry',
//       age: 8,
//       color: 'blue',
//       dogma_resource: 'timepieces',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 3,
//       resource_space_1: 'timepieces',
//       resource_space_2: 'timepieces',
//       resource_space_3: 'timepieces',
//       resource_space_4: '',
//     },
//     {
//       name: 'Skyscrapers',
//       age: 8,
//       color: 'yellow',
//       dogma_resource: 'crowns',
//       num_castles: 0,
//       num_crowns: 2,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 1,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'factories',
//       resource_space_3: 'crowns',
//       resource_space_4: 'crowns',
//     },
//     {
//       name: 'Socialism',
//       age: 8,
//       color: 'purple',
//       dogma_resource: 'leaves',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 3,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'leaves',
//       resource_space_2: '',
//       resource_space_3: 'leaves',
//       resource_space_4: 'leaves',
//     },
//     {
//       name: 'Corporations',
//       age: 8,
//       color: 'green',
//       dogma_resource: 'factories',
//       num_castles: 0,
//       num_crowns: 1,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 2,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'factories',
//       resource_space_3: 'factories',
//       resource_space_4: 'crowns',
//     },
//     {
//       name: 'Mass Media',
//       age: 8,
//       color: 'green',
//       dogma_resource: 'lightbulbs',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 2,
//       num_factories: 0,
//       num_timepieces: 1,
//       resource_space_1: 'lightbulbs',
//       resource_space_2: '',
//       resource_space_3: 'timepieces',
//       resource_space_4: 'lightbulbs',
//     },
//     {
//       name: 'Empiricism',
//       age: 8,
//       color: 'purple',
//       dogma_resource: 'lightbulbs',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 3,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'lightbulbs',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: 'lightbulbs',
//       resource_space_4: '',
//     },
//     {
//       name: 'Quantum Theory',
//       age: 8,
//       color: 'blue',
//       dogma_resource: 'timepieces',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 3,
//       resource_space_1: 'timepieces',
//       resource_space_2: 'timepieces',
//       resource_space_3: 'timepieces',
//       resource_space_4: '',
//     },
//     {
//       name: 'Computers',
//       age: 9,
//       color: 'blue',
//       dogma_resource: 'timepieces',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 1,
//       num_timepieces: 2,
//       resource_space_1: 'timepieces',
//       resource_space_2: '',
//       resource_space_3: 'timepieces',
//       resource_space_4: 'factories',
//     },
//     {
//       name: 'Collaboration',
//       age: 9,
//       color: 'green',
//       dogma_resource: 'crowns',
//       num_castles: 0,
//       num_crowns: 2,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 1,
//       resource_space_1: '',
//       resource_space_2: 'crowns',
//       resource_space_3: 'timepieces',
//       resource_space_4: 'crowns',
//     },
//     {
//       name: 'Genetics',
//       age: 9,
//       color: 'blue',
//       dogma_resource: 'lightbulbs',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 3,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'lightbulbs',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: 'lightbulbs',
//       resource_space_4: '',
//     },
//     {
//       name: 'Services',
//       age: 9,
//       color: 'purple',
//       dogma_resource: 'leaves',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 3,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'leaves',
//       resource_space_3: 'leaves',
//       resource_space_4: 'leaves',
//     },
//     {
//       name: 'Specialization',
//       age: 9,
//       color: 'purple',
//       dogma_resource: 'factories',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 1,
//       num_lightbulbs: 0,
//       num_factories: 2,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'factories',
//       resource_space_3: 'leaves',
//       resource_space_4: 'factories',
//     },
//     {
//       name: 'Suburbia',
//       age: 9,
//       color: 'yellow',
//       dogma_resource: 'leaves',
//       num_castles: 0,
//       num_crowns: 1,
//       num_leaves: 2,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'crowns',
//       resource_space_3: 'leaves',
//       resource_space_4: 'leaves',
//     },
//     {
//       name: 'Ecology',
//       age: 9,
//       color: 'yellow',
//       dogma_resource: 'lightbulbs',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 1,
//       num_lightbulbs: 2,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: 'leaves',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: 'lightbulbs',
//       resource_space_4: '',
//     },
//     {
//       name: 'Fission',
//       age: 9,
//       color: 'red',
//       dogma_resource: 'timepieces',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 3,
//       resource_space_1: '',
//       resource_space_2: 'timepieces',
//       resource_space_3: 'timepieces',
//       resource_space_4: 'timepieces',
//     },
//     {
//       name: 'Satellites',
//       age: 9,
//       color: 'green',
//       dogma_resource: 'timepieces',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 3,
//       resource_space_1: '',
//       resource_space_2: 'timepieces',
//       resource_space_3: 'timepieces',
//       resource_space_4: 'timepieces',
//     },
//     {
//       name: 'Composites',
//       age: 9,
//       color: 'red',
//       dogma_resource: 'factories',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 3,
//       num_timepieces: 0,
//       resource_space_1: 'factories',
//       resource_space_2: 'factories',
//       resource_space_3: '',
//       resource_space_4: 'factories',
//     },
//     {
//       name: 'Robotics',
//       age: 10,
//       color: 'red',
//       dogma_resource: 'factories',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 2,
//       num_timepieces: 1,
//       resource_space_1: '',
//       resource_space_2: 'factories',
//       resource_space_3: 'timepieces',
//       resource_space_4: 'factories',
//     },
//     {
//       name: 'Bioengineering',
//       age: 10,
//       color: 'blue',
//       dogma_resource: 'timepieces',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 1,
//       num_factories: 0,
//       num_timepieces: 2,
//       resource_space_1: 'lightbulbs',
//       resource_space_2: 'timepieces',
//       resource_space_3: 'timepieces',
//       resource_space_4: '',
//     },
//     {
//       name: 'Databases',
//       age: 10,
//       color: 'green',
//       dogma_resource: 'timepieces',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 3,
//       resource_space_1: '',
//       resource_space_2: 'timepieces',
//       resource_space_3: 'timepieces',
//       resource_space_4: 'timepieces',
//     },
//     {
//       name: 'Miniaturization',
//       age: 10,
//       color: 'red',
//       dogma_resource: 'lightbulbs',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 2,
//       num_factories: 0,
//       num_timepieces: 1,
//       resource_space_1: '',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: 'timepieces',
//       resource_space_4: 'lightbulbs',
//     },
//     {
//       name: 'Software',
//       age: 10,
//       color: 'blue',
//       dogma_resource: 'timepieces',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 3,
//       resource_space_1: 'timepieces',
//       resource_space_2: 'timepieces',
//       resource_space_3: 'timepieces',
//       resource_space_4: '',
//     },
//     {
//       name: 'Self Service',
//       age: 10,
//       color: 'green',
//       dogma_resource: 'crowns',
//       num_castles: 0,
//       num_crowns: 3,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'crowns',
//       resource_space_3: 'crowns',
//       resource_space_4: 'crowns',
//     },
//     {
//       name: 'A.I.',
//       age: 10,
//       color: 'purple',
//       dogma_resource: 'lightbulbs',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 2,
//       num_factories: 0,
//       num_timepieces: 1,
//       resource_space_1: 'lightbulbs',
//       resource_space_2: 'lightbulbs',
//       resource_space_3: 'timepieces',
//       resource_space_4: '',
//     },
//     {
//       name: 'Stem Cells',
//       age: 10,
//       color: 'yellow',
//       dogma_resource: 'leaves',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 3,
//       num_lightbulbs: 0,
//       num_factories: 0,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'leaves',
//       resource_space_3: 'leaves',
//       resource_space_4: 'leaves',
//     },
//     {
//       name: 'Globalization',
//       age: 10,
//       color: 'yellow',
//       dogma_resource: 'factories',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 0,
//       num_factories: 3,
//       num_timepieces: 0,
//       resource_space_1: '',
//       resource_space_2: 'factories',
//       resource_space_3: 'factories',
//       resource_space_4: 'factories',
//     },
//     {
//       name: 'The Internet',
//       age: 10,
//       color: 'purple',
//       dogma_resource: 'timepieces',
//       num_castles: 0,
//       num_crowns: 0,
//       num_leaves: 0,
//       num_lightbulbs: 1,
//       num_factories: 0,
//       num_timepieces: 2,
//       resource_space_1: '',
//       resource_space_2: 'timepieces',
//       resource_space_3: 'timepieces',
//       resource_space_4: 'lightbulbs',
//     },
//   ],
// };
